---
driver:
  name: vagrant
  customize:
    memory: 5120
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 8042, host: 8042}]
  - ["forwarded_port", {guest: 8080, host: 8080}]
  - ["forwarded_port", {guest: 8088, host: 8088}]
  - ["forwarded_port", {guest: 50070, host: 50070}]
  - ["forwarded_port", {guest: 50075, host: 50075}]
  - ["private_network", ip: "192.168.0.2"]

provisioner:
  name: chef_solo

platforms:
# - name: centos-6.5
# - name: ubuntu-12.04
  - name: ubuntu-14.04
  

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[hadoop::install]
      - recipe[hadoop::nn]
      - recipe[hadoop::rm]
      - recipe[hadoop::dn]
      - recipe[hadoop::nm]
      - recipe[hadoop::jhs]
      - recipe[saasfee::install]
      - recipe[saasfee::hiway_client]
      - recipe[saasfee::hiway_worker]
#      - recipe[saasfee::galaxy_worker]
      - recipe[saasfee::cuneiform_client]
      - recipe[saasfee::cuneiform_worker]
      - recipe[saasfee::helloworld_client]
#      - recipe[saasfee::helloworld_run_loc]
#      - recipe[saasfee::wordcount_client]
#      - recipe[saasfee::wordcount_run_loc]
#      - recipe[saasfee::montage_synth_client]
#      - recipe[saasfee::montage_synth_run_hw]
#      - recipe[saasfee::galaxy101_client]
#      - recipe[saasfee::galaxy101_worker]
#      - recipe[saasfee::galaxy101_run_hw]
      - recipe[saasfee::variantcall_client]
      - recipe[saasfee::variantcall_worker]
#      - recipe[saasfee::variantcall_run_hw]
#      - recipe[saasfee::variantcall_scale_client]
#      - recipe[saasfee::variantcall_scale_worker]
#      - recipe[saasfee::RNAseq_client]
#      - recipe[saasfee::RNAseq_worker]
#      - recipe[saasfee::montage_m17_4_client]
#      - recipe[saasfee::montage_m17_4_worker]

    attributes:
         hadoop:
            container_cleanup_delay_sec: "604800"
            version: "2.7.1"
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            cluster: vagrant
            yarn:
              user: 'vagrant'
              vcores: "2"
              nm:
                memory_mbs: "5632"
            mr:
              user: 'vagrant'
         saasfee:
           user: 'vagrant'
           hiway:
             worker:
               vcores: "2"
               memory_mb: "5120"
           variantcall:
             reference:
               id: "hg19"
               chromosomes: ['chr22', 'chrY']
               scale:
                 nsamples: 1
                 nruns: 1
           private_ips: ["10.0.2.15"]
           public_ips: ["10.0.2.15"]
         hdfs:
           user: 'vagrant'
         kmon:
           private_ips: ["10.0.2.15"]
           public_ips: ["10.0.2.15"]
         kagent:
           private_ips: ["10.0.2.15"]
           public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
